workflows:
  build:
    name: Build Android APK
    instance_type: mac_mini_m2
    environment:
      flutter: 3.27.4
      gradle: 8.10.2
    triggering:
      events:
        - push
    steps:
      - name: Build
        script: |
          flutter build apk --release
